In [6]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
ran_t=torch.rand(5,4)

In [ ]:
ran_t

tensor([[0.6239, 0.3829, 0.2417, 0.4236],
        [0.5917, 0.1626, 0.0709, 0.0766],
        [0.3870, 0.9813, 0.1663, 0.0945],
        [0.9131, 0.0756, 0.1223, 0.1422],
        [0.8675, 0.4720, 0.5659, 0.2956]])

In [7]:
df=pd.read_csv('/content/breastCancerDataset.csv')

In [8]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [9]:
df.shape

(569, 33)

In [11]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [12]:
df.dtypes

id                           int64
diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
Unnamed: 32                float64
dtype: object

In [14]:
df.drop(["id","Unnamed: 32"],inplace=True,axis=1)

In [15]:
df.isnull().sum()

diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [17]:
X=df.drop("diagnosis",axis=1)

In [18]:
Y=df["diagnosis"]

In [20]:
X

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [21]:
Y

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [23]:
#splitting the dataset
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,
                                               test_size=0.2,
                                               random_state=42)

In [26]:
#scaling the dataset
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [27]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [29]:
Y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [31]:
labelencode=LabelEncoder()
Y_train=labelencode.fit_transform(Y_train)
Y_test=labelencode.transform(Y_test)

In [32]:
#now we will convert arrays to tensors
X_train=torch.from_numpy(X_train)
X_test=torch.from_numpy(X_test)
Y_train=torch.from_numpy(Y_train)
Y_test=torch.from_numpy(Y_test)

In [33]:
X_train.shape

torch.Size([455, 30])

In [34]:
Y_train.shape

torch.Size([455])

#Define The Model

In [64]:
class simpleModel():
  def __init__(self):
    self.weights=torch.rand(X.shape[1],dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,x):
    matmul=torch.matmul(x,self.weights)+self.bias
    y_pred=torch.sigmoid(matmul)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(Y_train * torch.log(y_pred) + (1 - Y_train) * torch.log(1 - y_pred)).mean()
    return loss

#Parameters

In [65]:
lr=0.01 #learning Rate
epochs=30 #number of epochs

#Training Pipeline

In [66]:
#Create Model
model=simpleModel()

for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(X_train)

  #loss calculate
  loss=model.loss_function(y_pred,Y_train)
  print(f"Epoch {epoch+1} | Loss: {loss.item()}")

  #backward pass
  loss.backward()
  # parameters update
  with torch.no_grad():
    model.weights -= lr * model.weights.grad
    model.bias -= lr * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss for each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch 1 | Loss: 0.5962308330683225
Epoch: 1, Loss: 0.5962308330683225
Epoch 2 | Loss: 0.5948669739413703
Epoch: 2, Loss: 0.5948669739413703
Epoch 3 | Loss: 0.5935061687128009
Epoch: 3, Loss: 0.5935061687128009
Epoch 4 | Loss: 0.5921484111304822
Epoch: 4, Loss: 0.5921484111304822
Epoch 5 | Loss: 0.5907936949275296
Epoch: 5, Loss: 0.5907936949275296
Epoch 6 | Loss: 0.5894420138277658
Epoch: 6, Loss: 0.5894420138277658
Epoch 7 | Loss: 0.5880933615447462
Epoch: 7, Loss: 0.5880933615447462
Epoch 8 | Loss: 0.5867477317843128
Epoch: 8, Loss: 0.5867477317843128
Epoch 9 | Loss: 0.5854051182429079
Epoch: 9, Loss: 0.5854051182429079
Epoch 10 | Loss: 0.584065514610863
Epoch: 10, Loss: 0.584065514610863
Epoch 11 | Loss: 0.5827289145735725
Epoch: 11, Loss: 0.5827289145735725
Epoch 12 | Loss: 0.5813953118094798
Epoch: 12, Loss: 0.5813953118094798
Epoch 13 | Loss: 0.5800646999957363
Epoch: 13, Loss: 0.5800646999957363
Epoch 14 | Loss: 0.5787370728084299
Epoch: 14, Loss: 0.5787370728084299
Epoch 15 | L

In [67]:
model.weights

tensor([ 0.9923,  0.2304,  0.0251,  0.9148,  0.7140, -0.0219,  0.2451,  0.5326,
         0.8156,  0.8923,  0.4153,  0.3634,  0.7248,  0.9563,  0.0922,  0.1892,
         0.8689,  0.2818,  0.7578,  0.9006,  0.8797,  0.0606,  0.2209,  1.0109,
         0.0909,  0.3212,  0.7785,  0.0784,  0.0995,  0.5852],
       dtype=torch.float64, requires_grad=True)

In [68]:
model.bias

tensor([-0.0061], dtype=torch.float64, requires_grad=True)

#Evaluation

In [75]:
with torch.no_grad():
  y_pred=model.forward(X_test)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred==Y_test).float().mean()
  print(f"Accuracy:{accuracy.item()}\n")
  print(y_pred)

Accuracy:0.9035087823867798

tensor([0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
        0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
        1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1.,
        0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1.,
        0., 0., 1., 0., 0., 1.])
